# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 121)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_add = QtWidgets.QPushButton(self.widget)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout.addWidget(self.pushButton_add)
        self.pushButton_list = QtWidgets.QPushButton(self.widget)
        self.pushButton_list.setObjectName("pushButton_list")
        self.horizontalLayout.addWidget(self.pushButton_list)
        self.pushButton_list_brand = QtWidgets.QPushButton(self.widget)
        self.pushButton_list_brand.setObjectName("pushButton_list_brand")
        self.horizontalLayout.addWidget(self.pushButton_list_brand)
        self.pushButton_list_model = QtWidgets.QPushButton(self.widget)
        self.pushButton_list_model.setObjectName("pushButton_list_model")
        self.horizontalLayout.addWidget(self.pushButton_list_model)
        self.pushButton_average = QtWidgets.QPushButton(self.widget)
        self.pushButton_average.setObjectName("pushButton_average")
        self.horizontalLayout.addWidget(self.pushButton_average)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_add.setText(_translate("MainWindow", "Add Vehicle"))
        self.pushButton_list.setText(_translate("MainWindow", "List Vehicles"))
        self.pushButton_list_brand.setText(_translate("MainWindow", "List Vehicles by Brand"))
        self.pushButton_list_model.setText(_translate("MainWindow", "List Vehicles by Model"))
        self.pushButton_average.setText(_translate("MainWindow", "Average Vehicles price by Brand"))
